# Generated by Django 2.2.2 on 2019-07-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackgoUnivEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=100)),
                ('univ_entrance_type', models.CharField(max_length=100)),
                ('univ_entrance_name', models.CharField(max_length=100)),
                ('univ_url', models.URLField(verbose_name='University URL')),
            ],
        ),
        migrations.DeleteModel(
            name='BlackgoBlog',
        ),
        migrations.AlterField(
            model_name='blackgocafe',
            name='cafe_description',
            field=models.CharField(max_length=200),
        ),
    ]
