# Generated by Django 2.2.2 on 2019-07-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0002_auto_20190704_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackgoSampleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.CharField(max_length=200)),
                ('site_url', models.URLField(verbose_name='Sample Question URL')),
            ],
        ),
    ]
