# Generated by Django 2.2.2 on 2019-07-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0003_blackgosamplequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackgoOnlineAcademy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.CharField(max_length=200)),
                ('site_sample_url', models.URLField(verbose_name='Sample Question URL')),
                ('site_url', models.URLField(verbose_name='Site URL')),
            ],
        ),
        migrations.DeleteModel(
            name='BlackgoSampleQuestion',
        ),
    ]
