# Generated by Django 2.2.2 on 2019-07-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0004_auto_20190711_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackgoonlineacademy',
            name='site_sample_url',
        ),
    ]
