# Generated by Django 2.2.2 on 2019-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0005_remove_blackgoonlineacademy_site_sample_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackgoonlineacademy',
            name='offline_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blackgoonlineacademy',
            name='site_url',
            field=models.URLField(),
        ),
    ]
